### Add a New Post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "Sample Post",
  "content": "This is a sample post content.",
  "sender": "user001"
}

### Get All Posts
GET http://localhost:3000/api/posts

### Get a Post by ID
GET http://localhost:3000/api/posts/676d4cf23d6a58a1e4049126

### Get Posts by Sender
GET http://localhost:3000/api/posts?sender=user001

### Update a Post
PUT http://localhost:3000/api/posts/676d4cf23d6a58a1e4049126
Content-Type: application/json

{
  "title": "Updated Sample Post",
  "content": "This is the updated content of the sample post."
}
