### Add a New Post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "Sample Post",
  "content": "This is a sample post content.",
  "sender": "user001"
}

### Get All Posts
GET http://localhost:3000/api/posts

### Get a Post by ID
GET http://localhost:3000/api/posts/676d4cf23d6a58a1e4049126

### Get Posts by Sender
GET http://localhost:3000/api/posts?sender=user001

### Update a Post
PUT http://localhost:3000/api/posts/676d4cf23d6a58a1e4049126
Content-Type: application/json

{
  "title": "Updated Sample Post",
  "content": "This is the updated content of the sample post."
}

### Add a New Comment
POST http://localhost:3000/api/comments
Content-Type: application/json

{
  "postId": "676d4cf23d6a58a1e4049126",
  "content": "This is a comment on the sample post.",
  "author": "user002"
}

### Get All Comments for a Post
GET http://localhost:3000/api/comments?postId=63a9f0ea7b51066c46c9525d

### Update a Comment
PUT http://localhost:3000/api/comments/676d61e6864f7e93a7feab5c
Content-Type: application/json

{
  "content": "This is the updated content of the comment."
}

### Delete a Comment
DELETE http://localhost:3000/api/comments/676d61e6864f7e93a7feab5c